<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArchGuard.Domain\ArchGuard.Domain.csproj" />
    <ProjectReference Include="..\ArchGuard.Infrastructure\ArchGuard.Infrastructure.csproj" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.*" />
  </ItemGroup>
</Project>
